//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Logica.wsObligatorioCliente {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Service1Soap", Namespace="http://tempuri.org/")]
    public partial class Service1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback darPersonaOperationCompleted;
        
        private System.Threading.SendOrPostCallback esAdminOperationCompleted;
        
        private System.Threading.SendOrPostCallback esPacienteOperationCompleted;
        
        private System.Threading.SendOrPostCallback esProfesionalOperationCompleted;
        
        private System.Threading.SendOrPostCallback eliminarPersonaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ingresarPersonaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ingresarPacienteOperationCompleted;
        
        private System.Threading.SendOrPostCallback ingresarProfesionalOperationCompleted;
        
        private System.Threading.SendOrPostCallback ingresarConsultorioOperationCompleted;
        
        private System.Threading.SendOrPostCallback ingresarAdminOperationCompleted;
        
        private System.Threading.SendOrPostCallback modificarPersonaOperationCompleted;
        
        private System.Threading.SendOrPostCallback modificarPacienteOperationCompleted;
        
        private System.Threading.SendOrPostCallback modificarProfesionalOperationCompleted;
        
        private System.Threading.SendOrPostCallback modificarConsultorioOperationCompleted;
        
        private System.Threading.SendOrPostCallback eliminarConsultorioOperationCompleted;
        
        private System.Threading.SendOrPostCallback darProfesionalOperationCompleted;
        
        private System.Threading.SendOrPostCallback darPacienteOperationCompleted;
        
        private System.Threading.SendOrPostCallback darAdminOperationCompleted;
        
        private System.Threading.SendOrPostCallback darConsultorioOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service1() {
            this.Url = global::Logica.Properties.Settings.Default.Logica_wsObligatorioCliente_Service1;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event darPersonaCompletedEventHandler darPersonaCompleted;
        
        /// <remarks/>
        public event esAdminCompletedEventHandler esAdminCompleted;
        
        /// <remarks/>
        public event esPacienteCompletedEventHandler esPacienteCompleted;
        
        /// <remarks/>
        public event esProfesionalCompletedEventHandler esProfesionalCompleted;
        
        /// <remarks/>
        public event eliminarPersonaCompletedEventHandler eliminarPersonaCompleted;
        
        /// <remarks/>
        public event ingresarPersonaCompletedEventHandler ingresarPersonaCompleted;
        
        /// <remarks/>
        public event ingresarPacienteCompletedEventHandler ingresarPacienteCompleted;
        
        /// <remarks/>
        public event ingresarProfesionalCompletedEventHandler ingresarProfesionalCompleted;
        
        /// <remarks/>
        public event ingresarConsultorioCompletedEventHandler ingresarConsultorioCompleted;
        
        /// <remarks/>
        public event ingresarAdminCompletedEventHandler ingresarAdminCompleted;
        
        /// <remarks/>
        public event modificarPersonaCompletedEventHandler modificarPersonaCompleted;
        
        /// <remarks/>
        public event modificarPacienteCompletedEventHandler modificarPacienteCompleted;
        
        /// <remarks/>
        public event modificarProfesionalCompletedEventHandler modificarProfesionalCompleted;
        
        /// <remarks/>
        public event modificarConsultorioCompletedEventHandler modificarConsultorioCompleted;
        
        /// <remarks/>
        public event eliminarConsultorioCompletedEventHandler eliminarConsultorioCompleted;
        
        /// <remarks/>
        public event darProfesionalCompletedEventHandler darProfesionalCompleted;
        
        /// <remarks/>
        public event darPacienteCompletedEventHandler darPacienteCompleted;
        
        /// <remarks/>
        public event darAdminCompletedEventHandler darAdminCompleted;
        
        /// <remarks/>
        public event darConsultorioCompletedEventHandler darConsultorioCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/darPersona", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void darPersona(long ci) {
            this.Invoke("darPersona", new object[] {
                        ci});
        }
        
        /// <remarks/>
        public void darPersonaAsync(long ci) {
            this.darPersonaAsync(ci, null);
        }
        
        /// <remarks/>
        public void darPersonaAsync(long ci, object userState) {
            if ((this.darPersonaOperationCompleted == null)) {
                this.darPersonaOperationCompleted = new System.Threading.SendOrPostCallback(this.OndarPersonaOperationCompleted);
            }
            this.InvokeAsync("darPersona", new object[] {
                        ci}, this.darPersonaOperationCompleted, userState);
        }
        
        private void OndarPersonaOperationCompleted(object arg) {
            if ((this.darPersonaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.darPersonaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/esAdmin", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool esAdmin(long ci) {
            object[] results = this.Invoke("esAdmin", new object[] {
                        ci});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void esAdminAsync(long ci) {
            this.esAdminAsync(ci, null);
        }
        
        /// <remarks/>
        public void esAdminAsync(long ci, object userState) {
            if ((this.esAdminOperationCompleted == null)) {
                this.esAdminOperationCompleted = new System.Threading.SendOrPostCallback(this.OnesAdminOperationCompleted);
            }
            this.InvokeAsync("esAdmin", new object[] {
                        ci}, this.esAdminOperationCompleted, userState);
        }
        
        private void OnesAdminOperationCompleted(object arg) {
            if ((this.esAdminCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.esAdminCompleted(this, new esAdminCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/esPaciente", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool esPaciente(long ci) {
            object[] results = this.Invoke("esPaciente", new object[] {
                        ci});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void esPacienteAsync(long ci) {
            this.esPacienteAsync(ci, null);
        }
        
        /// <remarks/>
        public void esPacienteAsync(long ci, object userState) {
            if ((this.esPacienteOperationCompleted == null)) {
                this.esPacienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnesPacienteOperationCompleted);
            }
            this.InvokeAsync("esPaciente", new object[] {
                        ci}, this.esPacienteOperationCompleted, userState);
        }
        
        private void OnesPacienteOperationCompleted(object arg) {
            if ((this.esPacienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.esPacienteCompleted(this, new esPacienteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/esProfesional", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool esProfesional(long ci) {
            object[] results = this.Invoke("esProfesional", new object[] {
                        ci});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void esProfesionalAsync(long ci) {
            this.esProfesionalAsync(ci, null);
        }
        
        /// <remarks/>
        public void esProfesionalAsync(long ci, object userState) {
            if ((this.esProfesionalOperationCompleted == null)) {
                this.esProfesionalOperationCompleted = new System.Threading.SendOrPostCallback(this.OnesProfesionalOperationCompleted);
            }
            this.InvokeAsync("esProfesional", new object[] {
                        ci}, this.esProfesionalOperationCompleted, userState);
        }
        
        private void OnesProfesionalOperationCompleted(object arg) {
            if ((this.esProfesionalCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.esProfesionalCompleted(this, new esProfesionalCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/eliminarPersona", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void eliminarPersona(long ci) {
            this.Invoke("eliminarPersona", new object[] {
                        ci});
        }
        
        /// <remarks/>
        public void eliminarPersonaAsync(long ci) {
            this.eliminarPersonaAsync(ci, null);
        }
        
        /// <remarks/>
        public void eliminarPersonaAsync(long ci, object userState) {
            if ((this.eliminarPersonaOperationCompleted == null)) {
                this.eliminarPersonaOperationCompleted = new System.Threading.SendOrPostCallback(this.OneliminarPersonaOperationCompleted);
            }
            this.InvokeAsync("eliminarPersona", new object[] {
                        ci}, this.eliminarPersonaOperationCompleted, userState);
        }
        
        private void OneliminarPersonaOperationCompleted(object arg) {
            if ((this.eliminarPersonaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.eliminarPersonaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ingresarPersona", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ingresarPersona(long ci, string nombre, string apellido, string celular, System.DateTime fechaNacimiento, string direccion, string contraseña, bool habilitado) {
            this.Invoke("ingresarPersona", new object[] {
                        ci,
                        nombre,
                        apellido,
                        celular,
                        fechaNacimiento,
                        direccion,
                        contraseña,
                        habilitado});
        }
        
        /// <remarks/>
        public void ingresarPersonaAsync(long ci, string nombre, string apellido, string celular, System.DateTime fechaNacimiento, string direccion, string contraseña, bool habilitado) {
            this.ingresarPersonaAsync(ci, nombre, apellido, celular, fechaNacimiento, direccion, contraseña, habilitado, null);
        }
        
        /// <remarks/>
        public void ingresarPersonaAsync(long ci, string nombre, string apellido, string celular, System.DateTime fechaNacimiento, string direccion, string contraseña, bool habilitado, object userState) {
            if ((this.ingresarPersonaOperationCompleted == null)) {
                this.ingresarPersonaOperationCompleted = new System.Threading.SendOrPostCallback(this.OningresarPersonaOperationCompleted);
            }
            this.InvokeAsync("ingresarPersona", new object[] {
                        ci,
                        nombre,
                        apellido,
                        celular,
                        fechaNacimiento,
                        direccion,
                        contraseña,
                        habilitado}, this.ingresarPersonaOperationCompleted, userState);
        }
        
        private void OningresarPersonaOperationCompleted(object arg) {
            if ((this.ingresarPersonaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ingresarPersonaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ingresarPaciente", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ingresarPaciente(long ci, string contactoEmergencia, string celularEmergencia, string emergenciaMovil, string mutualista) {
            this.Invoke("ingresarPaciente", new object[] {
                        ci,
                        contactoEmergencia,
                        celularEmergencia,
                        emergenciaMovil,
                        mutualista});
        }
        
        /// <remarks/>
        public void ingresarPacienteAsync(long ci, string contactoEmergencia, string celularEmergencia, string emergenciaMovil, string mutualista) {
            this.ingresarPacienteAsync(ci, contactoEmergencia, celularEmergencia, emergenciaMovil, mutualista, null);
        }
        
        /// <remarks/>
        public void ingresarPacienteAsync(long ci, string contactoEmergencia, string celularEmergencia, string emergenciaMovil, string mutualista, object userState) {
            if ((this.ingresarPacienteOperationCompleted == null)) {
                this.ingresarPacienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OningresarPacienteOperationCompleted);
            }
            this.InvokeAsync("ingresarPaciente", new object[] {
                        ci,
                        contactoEmergencia,
                        celularEmergencia,
                        emergenciaMovil,
                        mutualista}, this.ingresarPacienteOperationCompleted, userState);
        }
        
        private void OningresarPacienteOperationCompleted(object arg) {
            if ((this.ingresarPacienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ingresarPacienteCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ingresarProfesional", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ingresarProfesional(long ci, string especialidad) {
            this.Invoke("ingresarProfesional", new object[] {
                        ci,
                        especialidad});
        }
        
        /// <remarks/>
        public void ingresarProfesionalAsync(long ci, string especialidad) {
            this.ingresarProfesionalAsync(ci, especialidad, null);
        }
        
        /// <remarks/>
        public void ingresarProfesionalAsync(long ci, string especialidad, object userState) {
            if ((this.ingresarProfesionalOperationCompleted == null)) {
                this.ingresarProfesionalOperationCompleted = new System.Threading.SendOrPostCallback(this.OningresarProfesionalOperationCompleted);
            }
            this.InvokeAsync("ingresarProfesional", new object[] {
                        ci,
                        especialidad}, this.ingresarProfesionalOperationCompleted, userState);
        }
        
        private void OningresarProfesionalOperationCompleted(object arg) {
            if ((this.ingresarProfesionalCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ingresarProfesionalCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ingresarConsultorio", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ingresarConsultorio(string direccion, int fechaInicio, int fechaFin) {
            this.Invoke("ingresarConsultorio", new object[] {
                        direccion,
                        fechaInicio,
                        fechaFin});
        }
        
        /// <remarks/>
        public void ingresarConsultorioAsync(string direccion, int fechaInicio, int fechaFin) {
            this.ingresarConsultorioAsync(direccion, fechaInicio, fechaFin, null);
        }
        
        /// <remarks/>
        public void ingresarConsultorioAsync(string direccion, int fechaInicio, int fechaFin, object userState) {
            if ((this.ingresarConsultorioOperationCompleted == null)) {
                this.ingresarConsultorioOperationCompleted = new System.Threading.SendOrPostCallback(this.OningresarConsultorioOperationCompleted);
            }
            this.InvokeAsync("ingresarConsultorio", new object[] {
                        direccion,
                        fechaInicio,
                        fechaFin}, this.ingresarConsultorioOperationCompleted, userState);
        }
        
        private void OningresarConsultorioOperationCompleted(object arg) {
            if ((this.ingresarConsultorioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ingresarConsultorioCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ingresarAdmin", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ingresarAdmin(long ci) {
            this.Invoke("ingresarAdmin", new object[] {
                        ci});
        }
        
        /// <remarks/>
        public void ingresarAdminAsync(long ci) {
            this.ingresarAdminAsync(ci, null);
        }
        
        /// <remarks/>
        public void ingresarAdminAsync(long ci, object userState) {
            if ((this.ingresarAdminOperationCompleted == null)) {
                this.ingresarAdminOperationCompleted = new System.Threading.SendOrPostCallback(this.OningresarAdminOperationCompleted);
            }
            this.InvokeAsync("ingresarAdmin", new object[] {
                        ci}, this.ingresarAdminOperationCompleted, userState);
        }
        
        private void OningresarAdminOperationCompleted(object arg) {
            if ((this.ingresarAdminCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ingresarAdminCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/modificarPersona", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void modificarPersona(long ci, string nombre, string apellido, string celular, System.DateTime fechaNacimiento, string direccion, bool habilitado) {
            this.Invoke("modificarPersona", new object[] {
                        ci,
                        nombre,
                        apellido,
                        celular,
                        fechaNacimiento,
                        direccion,
                        habilitado});
        }
        
        /// <remarks/>
        public void modificarPersonaAsync(long ci, string nombre, string apellido, string celular, System.DateTime fechaNacimiento, string direccion, bool habilitado) {
            this.modificarPersonaAsync(ci, nombre, apellido, celular, fechaNacimiento, direccion, habilitado, null);
        }
        
        /// <remarks/>
        public void modificarPersonaAsync(long ci, string nombre, string apellido, string celular, System.DateTime fechaNacimiento, string direccion, bool habilitado, object userState) {
            if ((this.modificarPersonaOperationCompleted == null)) {
                this.modificarPersonaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnmodificarPersonaOperationCompleted);
            }
            this.InvokeAsync("modificarPersona", new object[] {
                        ci,
                        nombre,
                        apellido,
                        celular,
                        fechaNacimiento,
                        direccion,
                        habilitado}, this.modificarPersonaOperationCompleted, userState);
        }
        
        private void OnmodificarPersonaOperationCompleted(object arg) {
            if ((this.modificarPersonaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.modificarPersonaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/modificarPaciente", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void modificarPaciente(long ci, string contactoEmergencia, string celularEmergencia, string emergenciaMovil, string mutualista) {
            this.Invoke("modificarPaciente", new object[] {
                        ci,
                        contactoEmergencia,
                        celularEmergencia,
                        emergenciaMovil,
                        mutualista});
        }
        
        /// <remarks/>
        public void modificarPacienteAsync(long ci, string contactoEmergencia, string celularEmergencia, string emergenciaMovil, string mutualista) {
            this.modificarPacienteAsync(ci, contactoEmergencia, celularEmergencia, emergenciaMovil, mutualista, null);
        }
        
        /// <remarks/>
        public void modificarPacienteAsync(long ci, string contactoEmergencia, string celularEmergencia, string emergenciaMovil, string mutualista, object userState) {
            if ((this.modificarPacienteOperationCompleted == null)) {
                this.modificarPacienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnmodificarPacienteOperationCompleted);
            }
            this.InvokeAsync("modificarPaciente", new object[] {
                        ci,
                        contactoEmergencia,
                        celularEmergencia,
                        emergenciaMovil,
                        mutualista}, this.modificarPacienteOperationCompleted, userState);
        }
        
        private void OnmodificarPacienteOperationCompleted(object arg) {
            if ((this.modificarPacienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.modificarPacienteCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/modificarProfesional", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void modificarProfesional(long ci, string especialidad) {
            this.Invoke("modificarProfesional", new object[] {
                        ci,
                        especialidad});
        }
        
        /// <remarks/>
        public void modificarProfesionalAsync(long ci, string especialidad) {
            this.modificarProfesionalAsync(ci, especialidad, null);
        }
        
        /// <remarks/>
        public void modificarProfesionalAsync(long ci, string especialidad, object userState) {
            if ((this.modificarProfesionalOperationCompleted == null)) {
                this.modificarProfesionalOperationCompleted = new System.Threading.SendOrPostCallback(this.OnmodificarProfesionalOperationCompleted);
            }
            this.InvokeAsync("modificarProfesional", new object[] {
                        ci,
                        especialidad}, this.modificarProfesionalOperationCompleted, userState);
        }
        
        private void OnmodificarProfesionalOperationCompleted(object arg) {
            if ((this.modificarProfesionalCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.modificarProfesionalCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/modificarConsultorio", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void modificarConsultorio(long idConsultorio, string direccion, int fechaInicio, int fechaFin) {
            this.Invoke("modificarConsultorio", new object[] {
                        idConsultorio,
                        direccion,
                        fechaInicio,
                        fechaFin});
        }
        
        /// <remarks/>
        public void modificarConsultorioAsync(long idConsultorio, string direccion, int fechaInicio, int fechaFin) {
            this.modificarConsultorioAsync(idConsultorio, direccion, fechaInicio, fechaFin, null);
        }
        
        /// <remarks/>
        public void modificarConsultorioAsync(long idConsultorio, string direccion, int fechaInicio, int fechaFin, object userState) {
            if ((this.modificarConsultorioOperationCompleted == null)) {
                this.modificarConsultorioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnmodificarConsultorioOperationCompleted);
            }
            this.InvokeAsync("modificarConsultorio", new object[] {
                        idConsultorio,
                        direccion,
                        fechaInicio,
                        fechaFin}, this.modificarConsultorioOperationCompleted, userState);
        }
        
        private void OnmodificarConsultorioOperationCompleted(object arg) {
            if ((this.modificarConsultorioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.modificarConsultorioCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/eliminarConsultorio", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void eliminarConsultorio(long idConsultorio) {
            this.Invoke("eliminarConsultorio", new object[] {
                        idConsultorio});
        }
        
        /// <remarks/>
        public void eliminarConsultorioAsync(long idConsultorio) {
            this.eliminarConsultorioAsync(idConsultorio, null);
        }
        
        /// <remarks/>
        public void eliminarConsultorioAsync(long idConsultorio, object userState) {
            if ((this.eliminarConsultorioOperationCompleted == null)) {
                this.eliminarConsultorioOperationCompleted = new System.Threading.SendOrPostCallback(this.OneliminarConsultorioOperationCompleted);
            }
            this.InvokeAsync("eliminarConsultorio", new object[] {
                        idConsultorio}, this.eliminarConsultorioOperationCompleted, userState);
        }
        
        private void OneliminarConsultorioOperationCompleted(object arg) {
            if ((this.eliminarConsultorioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.eliminarConsultorioCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/darProfesional", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public VOProfesional darProfesional(long ced) {
            object[] results = this.Invoke("darProfesional", new object[] {
                        ced});
            return ((VOProfesional)(results[0]));
        }
        
        /// <remarks/>
        public void darProfesionalAsync(long ced) {
            this.darProfesionalAsync(ced, null);
        }
        
        /// <remarks/>
        public void darProfesionalAsync(long ced, object userState) {
            if ((this.darProfesionalOperationCompleted == null)) {
                this.darProfesionalOperationCompleted = new System.Threading.SendOrPostCallback(this.OndarProfesionalOperationCompleted);
            }
            this.InvokeAsync("darProfesional", new object[] {
                        ced}, this.darProfesionalOperationCompleted, userState);
        }
        
        private void OndarProfesionalOperationCompleted(object arg) {
            if ((this.darProfesionalCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.darProfesionalCompleted(this, new darProfesionalCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/darPaciente", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public VOPaciente darPaciente(long ced) {
            object[] results = this.Invoke("darPaciente", new object[] {
                        ced});
            return ((VOPaciente)(results[0]));
        }
        
        /// <remarks/>
        public void darPacienteAsync(long ced) {
            this.darPacienteAsync(ced, null);
        }
        
        /// <remarks/>
        public void darPacienteAsync(long ced, object userState) {
            if ((this.darPacienteOperationCompleted == null)) {
                this.darPacienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OndarPacienteOperationCompleted);
            }
            this.InvokeAsync("darPaciente", new object[] {
                        ced}, this.darPacienteOperationCompleted, userState);
        }
        
        private void OndarPacienteOperationCompleted(object arg) {
            if ((this.darPacienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.darPacienteCompleted(this, new darPacienteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/darAdmin", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public VOAdmin darAdmin(long ced) {
            object[] results = this.Invoke("darAdmin", new object[] {
                        ced});
            return ((VOAdmin)(results[0]));
        }
        
        /// <remarks/>
        public void darAdminAsync(long ced) {
            this.darAdminAsync(ced, null);
        }
        
        /// <remarks/>
        public void darAdminAsync(long ced, object userState) {
            if ((this.darAdminOperationCompleted == null)) {
                this.darAdminOperationCompleted = new System.Threading.SendOrPostCallback(this.OndarAdminOperationCompleted);
            }
            this.InvokeAsync("darAdmin", new object[] {
                        ced}, this.darAdminOperationCompleted, userState);
        }
        
        private void OndarAdminOperationCompleted(object arg) {
            if ((this.darAdminCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.darAdminCompleted(this, new darAdminCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/darConsultorio", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public VOConsultorio darConsultorio(long idConsultorio) {
            object[] results = this.Invoke("darConsultorio", new object[] {
                        idConsultorio});
            return ((VOConsultorio)(results[0]));
        }
        
        /// <remarks/>
        public void darConsultorioAsync(long idConsultorio) {
            this.darConsultorioAsync(idConsultorio, null);
        }
        
        /// <remarks/>
        public void darConsultorioAsync(long idConsultorio, object userState) {
            if ((this.darConsultorioOperationCompleted == null)) {
                this.darConsultorioOperationCompleted = new System.Threading.SendOrPostCallback(this.OndarConsultorioOperationCompleted);
            }
            this.InvokeAsync("darConsultorio", new object[] {
                        idConsultorio}, this.darConsultorioOperationCompleted, userState);
        }
        
        private void OndarConsultorioOperationCompleted(object arg) {
            if ((this.darConsultorioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.darConsultorioCompleted(this, new darConsultorioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class VOProfesional {
        
        private long ciField;
        
        private string nombreField;
        
        private string apellidoField;
        
        private System.DateTime fechaNacField;
        
        private string celularField;
        
        private bool habilitadoField;
        
        private string especialidadField;
        
        /// <remarks/>
        public long Ci {
            get {
                return this.ciField;
            }
            set {
                this.ciField = value;
            }
        }
        
        /// <remarks/>
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        public string Apellido {
            get {
                return this.apellidoField;
            }
            set {
                this.apellidoField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime FechaNac {
            get {
                return this.fechaNacField;
            }
            set {
                this.fechaNacField = value;
            }
        }
        
        /// <remarks/>
        public string Celular {
            get {
                return this.celularField;
            }
            set {
                this.celularField = value;
            }
        }
        
        /// <remarks/>
        public bool Habilitado {
            get {
                return this.habilitadoField;
            }
            set {
                this.habilitadoField = value;
            }
        }
        
        /// <remarks/>
        public string Especialidad {
            get {
                return this.especialidadField;
            }
            set {
                this.especialidadField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class VOConsultorio {
        
        private int idConsultorioField;
        
        private string direccionField;
        
        private int horaInicioField;
        
        private int horaFinField;
        
        /// <remarks/>
        public int IdConsultorio {
            get {
                return this.idConsultorioField;
            }
            set {
                this.idConsultorioField = value;
            }
        }
        
        /// <remarks/>
        public string Direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
            }
        }
        
        /// <remarks/>
        public int HoraInicio {
            get {
                return this.horaInicioField;
            }
            set {
                this.horaInicioField = value;
            }
        }
        
        /// <remarks/>
        public int HoraFin {
            get {
                return this.horaFinField;
            }
            set {
                this.horaFinField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class VOAdmin {
        
        private long ciField;
        
        private string nombreField;
        
        private string apellidoField;
        
        private System.DateTime fechaNacField;
        
        private string direccionField;
        
        private string celularField;
        
        private bool habilitadoField;
        
        /// <remarks/>
        public long Ci {
            get {
                return this.ciField;
            }
            set {
                this.ciField = value;
            }
        }
        
        /// <remarks/>
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        public string Apellido {
            get {
                return this.apellidoField;
            }
            set {
                this.apellidoField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime FechaNac {
            get {
                return this.fechaNacField;
            }
            set {
                this.fechaNacField = value;
            }
        }
        
        /// <remarks/>
        public string Direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
            }
        }
        
        /// <remarks/>
        public string Celular {
            get {
                return this.celularField;
            }
            set {
                this.celularField = value;
            }
        }
        
        /// <remarks/>
        public bool Habilitado {
            get {
                return this.habilitadoField;
            }
            set {
                this.habilitadoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class VOPaciente {
        
        private long ciField;
        
        private string nombreField;
        
        private string apellidoField;
        
        private System.DateTime fechaNacField;
        
        private string celularField;
        
        private bool habilitadoField;
        
        private string contactoEmergenciaField;
        
        private string celularEmergenciaField;
        
        private string emergenciaMovilField;
        
        private string mutualistaField;
        
        /// <remarks/>
        public long Ci {
            get {
                return this.ciField;
            }
            set {
                this.ciField = value;
            }
        }
        
        /// <remarks/>
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        public string Apellido {
            get {
                return this.apellidoField;
            }
            set {
                this.apellidoField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime FechaNac {
            get {
                return this.fechaNacField;
            }
            set {
                this.fechaNacField = value;
            }
        }
        
        /// <remarks/>
        public string Celular {
            get {
                return this.celularField;
            }
            set {
                this.celularField = value;
            }
        }
        
        /// <remarks/>
        public bool Habilitado {
            get {
                return this.habilitadoField;
            }
            set {
                this.habilitadoField = value;
            }
        }
        
        /// <remarks/>
        public string ContactoEmergencia {
            get {
                return this.contactoEmergenciaField;
            }
            set {
                this.contactoEmergenciaField = value;
            }
        }
        
        /// <remarks/>
        public string CelularEmergencia {
            get {
                return this.celularEmergenciaField;
            }
            set {
                this.celularEmergenciaField = value;
            }
        }
        
        /// <remarks/>
        public string EmergenciaMovil {
            get {
                return this.emergenciaMovilField;
            }
            set {
                this.emergenciaMovilField = value;
            }
        }
        
        /// <remarks/>
        public string Mutualista {
            get {
                return this.mutualistaField;
            }
            set {
                this.mutualistaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void darPersonaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void esAdminCompletedEventHandler(object sender, esAdminCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class esAdminCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal esAdminCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void esPacienteCompletedEventHandler(object sender, esPacienteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class esPacienteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal esPacienteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void esProfesionalCompletedEventHandler(object sender, esProfesionalCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class esProfesionalCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal esProfesionalCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void eliminarPersonaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void ingresarPersonaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void ingresarPacienteCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void ingresarProfesionalCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void ingresarConsultorioCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void ingresarAdminCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void modificarPersonaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void modificarPacienteCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void modificarProfesionalCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void modificarConsultorioCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void eliminarConsultorioCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void darProfesionalCompletedEventHandler(object sender, darProfesionalCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class darProfesionalCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal darProfesionalCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public VOProfesional Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((VOProfesional)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void darPacienteCompletedEventHandler(object sender, darPacienteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class darPacienteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal darPacienteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public VOPaciente Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((VOPaciente)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void darAdminCompletedEventHandler(object sender, darAdminCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class darAdminCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal darAdminCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public VOAdmin Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((VOAdmin)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void darConsultorioCompletedEventHandler(object sender, darConsultorioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class darConsultorioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal darConsultorioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public VOConsultorio Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((VOConsultorio)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591